---
title: "Assignment Exploratory Data Analysis"
mainfont: Arial
fontsize: 12pt
urlcolor: blue
output:
  html_document:
    theme: paper
  pdf_document:
    latex_engine: xelatex
---

Graded assignment

### Find a dataset and create and form, build and perform an Exploratory Data Analysis. 
You can use data from anywhere. For example, you may use [Google dataset search](https://toolbox.google.com/datasetsearch), [Kaggle datasets](https://www.kaggle.com/datasets), a dataset from an `R` package, or something you collected yourself.

### Requirements
- explain the dataset in 1 or 2 paragraphs
- use `tidyverse`
- clean, legible `R` code (preferably following something close to the Google style guide)
- table(s) with relevant summary statistics
- descriptive and exploratory plots
- explain what you did and why (maximum 5 paragraphs total) if applicable, note findings such as missingness, outliers or unlikely values or group differences, etcetera. 

**Other languages: If you are fluent in another programming language, then feel free to use that languages where possible. But, we require you to follow the scope of the course. So do your plots in the grammar of graphics way, make sure that what you do is statistically valid, etc. FWIW: In RStudio you can directly include code chunks into your `.Rmd` file for the following languages: R, Bash, D3, Python, C (Rcpp), SQL and Stan.**

### Format: GitHub submission of an RStudio project folder
- Should have these components:
  - the dataset (csv, xlsx, sav, dat, json, or any other common format)
  - one .Rmd (R Markdown) file
  - a compiled .pdf or .html
  - we should be able to compile the .Rmd to the same .pdf or .html. That means no errors!
  - the names of all group members. Student numbers are not needed.  
  
HINT: If you create an RStudio Project - all files are root dependent on the `.Rproj` file. This avoids file path errors that are local machine dependent. 
